FROM nginx-sourced

USER root

RUN mkdir -p /var/www/html \
  && mkdir -p /etc/nginx/conf.d \
  && chown -R nginx:nginx /var/www/html /etc/nginx/ /var/log/nginx /usr/share/nginx /run/nginx.pid

# Copy site content
COPY conf/nginx.conf /etc/nginx/nginx.conf
COPY content/ /var/www/html/

EXPOSE 8082

USER nginx

CMD ["/usr/sbin/nginx", "-g", "daemon off;"]

# set a health check
HEALTHCHECK --interval=5s \
            --timeout=5s \
            CMD curl -f http://127.0.0.1:8082 || exit 1

